server:
  port: 8081
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/
  instance:
    hostname: localhost

spring:
  application:
    name: GATEWAY-SERVER
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
      - id: MICRO-LABORATORIO
        uri: lb://MICRO-LABORATORIO
        predicates:
        - Path=/laboratorio/**
      - id: MICRO-MEDICAMENTO
        uri: lb://MICRO-MEDICAMENTO
        predicates:
        - Path=/medicamento/**